services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    restart: unless-stopped
    container_name: SocreAPI
    ports:
      - "8000:${PORT}"
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DIALECT: ${POSTGRES_DIALECT}
      SALT_ROUNDS: ${SALT_ROUNDS}
      SECRET_KEY_TOKEN: ${SECRET_KEY_TOKEN}
      SECRET_HASH_KEY_TABID: ${SECRET_HASH_KEY_TABID}
      TOKEN_EXPIRY_TIME: ${TOKEN_EXPIRY_TIME}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      COMMANTRY_UPDATE_TIME: ${COMMANTRY_UPDATE_TIME}
      IMPORTMARKET_API : ${IMPORTMARKET_API}
      SYSTEM_PLAYER_COUNT : ${SYSTEM_PLAYER_COUNT}
      SENTRY_DSN: ${SENTRY_DSN}
      ENABLE_SENTRY: ${ENABLE_SENTRY}
      SOCKET_ADMIN_USERNAME: ${SOCKET_ADMIN_USERNAME}
      SOCKET_ADMIN_PASSWORD: ${SOCKET_ADMIN_PASSWORD}
      IS_CRON_ENABLE: ${IS_CRON_ENABLE}
      PORT: ${PORT}