const configConstants = {
    IMPORTMARKET_API : "IMPORTAPIURI",
    FILE_UPLOAD_URL : "FILEUPLOADURI",
    PROJECT_NAME : "PROJECTCODE",
    COMMENTARY_EVENT_DAY_INTERVAL : "COMMENTARYEVENTDAYINTERVAL",	
}
module.exports = configConstants;