const configConstants = {
    IMPORTMARKET_API : "IMPORTAPIURI",
    FILE_UPLOAD_URL : "FILEUPLOADURI",
    PROJECT_NAME : "PROJECTCODE",
    COMMENTARY_EVENT_DAY_INTERVAL : "EVENTDAYINTERVAL",	
    MARKET_PREDICTOR : "MARKETPREDICTOR",
    PASSWORD : "PASSWORD",
    ISPREDICTORLOGGER : "ISPREDICTORLOGGER",
}
module.exports = configConstants;