const configConstants = {
    IMPORTMARKET_API : "IMPORTAPIURI",
    FILE_UPLOAD_URL : "FILEUPLOADURI",
    PROJECT_NAME : "PROJECTCODE",
    COMMENTARY_EVENT_DAY_INTERVAL : "EVENTDAYINTERVAL",	
    MARKET_PREDICTOR : "MARKETPREDICTOR",
    PASSWORD : "PASSWORD",
    ISPREDICTORLOGGER : "ISPREDICTORLOGGER",
    SCORECLIENTAPIURL : "SCORECLIENTAPIURL",
    DATAPROVIDERURL : "DATAPROVIDERURL",
    MARKETRTETHIRDPARTY : "MARKETRTETHIRDPARTY",
    INTERVAL_MarketTHIRDPARTY : "INTERVAL_MarketTHIRDPARTY",
}
module.exports = configConstants;