const ImgModuleConfig = {
  PageFormates: {
    type: "pageFormates",
    formate: ".jpg,.png,.jpeg",
    size: 0,
    height: 0,
    width: 0,
  },
  EventTypes: {
    type: "eventTypes",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Players: {
    type: "players",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Teams: {
    type: "teams",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Competitions: {
    type: "competitions",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Blocks: {
    type: "blocks",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  CK_Images: {
    type: "ck_images",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  News: {
    type: "news",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Banner: {
    type: "banner",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Advertise: { 
    type: "advertise",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Notification: {
    type: "notification",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  ClientVideo: {
    type: "clientVideo",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  SocialMedia: {
    type: "socialMedia",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Article: {
    type: "article",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  LibraryImage: {
    type: "photoLibrary",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  VideoLibrary: {
    type: "videoLibrary",
    formate: ".mp4,.webm,.avi,.mkv,.mov,.flv,.3gp,.ogv",
    size: 0,
    height: 0,
    width: 0,
  },
  ShotType: {
    type: "shotType",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  PlayerAndJersey: {
    type: "PlayerAndJersey",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Flag: {
    type: "Flag",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  CardType: {
    type: "CardType",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  Whitelable: {
    type: "Whitelable",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  WhitelabelLogo: {
    type: "whitelabelLogo",
    formate: ".jpg,.png,.jpeg,.svg,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  WhitelabelFavicon: {
    type: "whitelabelFavicon",
    formate: ".ico,.png,.jpg,.jpeg,.svg",
    size: 0,
    height: 0,
    width: 0,
  },
  TeamMatchType: {
    type: "TeamMatchType",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
  PaymentMethod: {
    type: "paymentMethod",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
   Default: {
    type: "Default",
    formate: ".jpg,.png,.jpeg,.avif,.webp",
    size: 0,
    height: 0,
    width: 0,
  },
};
module.exports = {
  ImgModuleConfig,
};
